-- 선수 테이블 생성
CREATE TABLE PLAYERS (
    PLAYER_ID INT PRIMARY KEY IDENTITY(1,1),
    NAME VARCHAR(100)
);
GO

-- 매치 테이블 생성
CREATE TABLE MATCHES (
    MATCH_ID INT PRIMARY KEY IDENTITY(1,1),
    OPPONENT VARCHAR(100),
    LOCATION VARCHAR(100),
    MATCH_DATE DATE
);
GO

-- 중간 테이블 생성 (매치에 참가한 선수들의 정보)
CREATE TABLE MATCH_PLAYERS (
    MATCH_PLAYER_ID INT PRIMARY KEY IDENTITY(1,1),
    MATCH_ID INT,
    PLAYER_ID INT,
    FOREIGN KEY (MATCH_ID) REFERENCES MATCHES(MATCH_ID),
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYERS(PLAYER_ID)
);
GO

-- 골 테이블 생성
CREATE TABLE GOALS (
    GOAL_ID INT PRIMARY KEY IDENTITY(1,1),
    PLAYER_ID INT,
	MATCH_ID INT,
	GOAL_QUARTER INT,
    FOREIGN KEY (MATCH_ID) REFERENCES MATCHES(MATCH_ID),
	FOREIGN KEY (PLAYER_ID) REFERENCES PLAYERS(PLAYER_ID)
);
GO

-- 어시스트 테이블 생성
CREATE TABLE ASSISTS (
    ASSISTS_ID INT PRIMARY KEY IDENTITY(1,1),
    PLAYER_ID INT,
	MATCH_ID INT,
    ASSISTS_QUARTER INT,
	GOAL_ID INT,
	FOREIGN KEY (GOAL_ID) REFERENCES GOALS(GOAL_ID),
    FOREIGN KEY (MATCH_ID) REFERENCES MATCHES(MATCH_ID),
	FOREIGN KEY (PLAYER_ID) REFERENCES PLAYERS(PLAYER_ID)
);
GO

DROP TABLE ASSISTS
