CREATE PROCEDURE P_INSERT
    @PROFILE_PICTURE VARCHAR(MAX),
    @NAME VARCHAR(50),
    @PHONE_NUMBER VARCHAR(50),
    @CONTACT_GROUP VARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    SET @PROFILE_PICTURE = REPLACE(@PROFILE_PICTURE, '''', '');

    INSERT INTO Contacts (PROFILE_PICTURE, NAME, PHONE_NUMBER, CONTACT_GROUP)
    VALUES (@PROFILE_PICTURE, @NAME, @PHONE_NUMBER, @CONTACT_GROUP);
END
