CREATE PROCEDURE UTB_EMPUSER_D
(
    @UserID VARCHAR(50),
    @Result INT OUTPUT
)
AS
BEGIN
    IF EXISTS (SELECT 1 FROM UTB_EMPUSER WHERE ID = @UserID)
    BEGIN
        DELETE FROM UTB_EMPUSER WHERE ID = @UserID
        SET @Result = 1
    END
END
