CREATE PROCEDURE UTB_EMPUSER_I
(
    @ID VARCHAR(50),
    @PW VARCHAR(50),
    @NAME VARCHAR(50),
    @CREATE_DTTM DATETIME,
    @SAVE_DTTM DATETIME,
    @Result INT OUTPUT
)
AS
BEGIN
    IF EXISTS (SELECT 1 FROM UTB_EMPUSER WHERE ID = @ID)
    BEGIN
        SET @Result = -1;
    END
    ELSE
    BEGIN
        INSERT INTO UTB_EMPUSER (ID, PW, NAME, CREATE_DTTM, SAVE_DTTM)
        VALUES (@ID, @PW, @NAME, @CREATE_DTTM, @SAVE_DTTM);

        SET @Result = 1;
    END
END