CREATE PROCEDURE UTB_EMPUSER_L
(
    @ID VARCHAR(50),
    @PW VARCHAR(50),
    @UserName VARCHAR(50) OUTPUT
)
AS
BEGIN
    IF EXISTS (SELECT 1 FROM UTB_EMPUSER WHERE ID = @ID AND PW = @PW)
    BEGIN
        SELECT @UserName = NAME FROM UTB_EMPUSER WHERE ID = @ID;
    END
END