CREATE PROCEDURE UTB_EMPUSER_L
(
    @P_ID VARCHAR(50),
    @P_PW VARCHAR(50),
    @P_NAME VARCHAR(50) OUTPUT
)
AS
BEGIN
    IF EXISTS (SELECT 1 FROM UTB_EMPUSER WITH(NOLOCK) WHERE ID = @P_ID AND PW = @P_PW)
    BEGIN
        SELECT @P_NAME = NAME FROM UTB_EMPUSER WHERE ID = @P_ID;
    END
END