CREATE PROCEDURE UTB_EMPUSER_D
(
    @P_ID VARCHAR(50),
    @Result INT OUTPUT
)
AS
BEGIN
    IF EXISTS (SELECT 1 FROM UTB_EMPUSER WITH(NOLOCK) WHERE ID = @P_ID)
    BEGIN
        DELETE FROM UTB_EMPUSER WHERE ID = @P_ID
        SET @Result = 1
    END
END
