  CREATE PROCEDURE UTB_EMPUSER_I
(
    @P_ID VARCHAR(50),
    @P_PW VARCHAR(50),
    @P_NAME VARCHAR(50),
    @P_CREATE_DTTM DATETIME,
    @P_SAVE_DTTM DATETIME,
    @Result INT OUTPUT
)
AS
BEGIN
    IF EXISTS (SELECT 1 FROM UTB_EMPUSER WITH(NOLOCK) WHERE ID = @P_ID)
    BEGIN
        SET @Result = -1;
    END
    ELSE
    BEGIN
        INSERT INTO UTB_EMPUSER (ID, PW, NAME, CREATE_DTTM, SAVE_DTTM)
        VALUES (@P_ID, @P_PW, @P_NAME, @P_CREATE_DTTM, @P_SAVE_DTTM);

        SET @Result = 1;
    END
END